on:
  schedule:
    - cron: '0 8 */1 * *'
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

name: Fetch MDS blob, dump AAGUIDs and push to GitHub Pages

jobs:
  dump-aaguids:
    runs-on: ubuntu-latest
    name: Dump latest AAGUIDs
    steps:
      - uses: actions/checkout@v6
      - name: Dump AAGUIDs (MDS)
        run: ./scripts/ConvertFrom-FIDOMDS.ps1
        shell: pwsh
      - name: Dump AAGUIDs (combined_aaguid)
        run: ./scripts/ConvertFrom-PasskeyBlob.ps1
        shell: pwsh
      - name: Commit and push changes
        run: |
          git config --global user.name 'AAGuid dump bot'
          git config --global user.email 'nicolonsky@users.noreply.github.com'
          git add .
          git commit -am "AAGuid dump"
          git push
        continue-on-error: true
  build:
    needs: dump-aaguids
    runs-on: ubuntu-latest
    name: Build React APP
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
      
